# Generated by Django 4.1.2 on 2022-10-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField(max_length=250)),
                ('num2', models.IntegerField(choices=[(1, 'Uno'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco'), (6, 'Seis'), (7, 'Siete'), (8, 'Ocho'), (9, 'Nueve'), (10, 'Dies')])),
            ],
        ),
    ]
