# Generated by Django 4.1.2 on 2022-10-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='div',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='multi',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='poten',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='resta',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='suma',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='num1',
            field=models.IntegerField(max_length=2),
        ),
    ]
